# Generated by Django 4.2.6 on 2023-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_uploadedfile_alter_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.CharField(max_length=200),
        ),
    ]
